apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainGrafana }}
      secretName: grafana-cert
  rules:
    - host: {{ .Values.domainGrafana }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promrub-{{ .Values.envAlias }}-konga
                port:
                  number: 80
