apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influx-cert
spec:
  secretName: influx-cert
  dnsNames:
    - {{ .Values.domainInflux }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
