apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influx-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: influx-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: DOCKER_INFLUXDB_INIT_USERNAME
    remoteRef:
      key: initial-secret
      property: INFLUXDB_USER

  - secretKey: DOCKER_INFLUXDB_INIT_PASSWORD
    remoteRef:
      key: initial-secret
      property: INFLUXDB_PASSWORD

  - secretKey: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    remoteRef:
      key: initial-secret
      property: INFLUXDB_TOKEN

  - secretKey: INFLUXDB_CLOUD_TOKEN
    remoteRef:
      key: initial-secret
      property: INFLUXDB_CLOUD_TOKEN