apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-filter-cm
  annotations:
    checksum/config1: {{ .Files.Get "scripts/process_kafka_to_influxdb.vrl" | sha256sum }}
    checksum/config2: {{ .Files.Get "scripts/process_kafka_to_loki.vrl" | sha256sum }}
data:
  process_kafka_to_influxdb.vrl: |-
{{ .Files.Get "scripts/process_kafka_to_influxdb.vrl" |  indent 4 }}
  process_kafka_to_loki.vrl: |-
{{ .Files.Get "scripts/process_kafka_to_loki.vrl" |  indent 4 }}
