{{- with .Values.kafka.cluster }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .name }}
spec:
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    logging: debug
    enableSaramaLogging: true
  kafka:
    template:
    replicas: {{ .kafka.replicas }}
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .kafka.diskSize }}
        deleteClaim: false
  zookeeper:
    template:
    replicas: {{ .zooKeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .zooKeeper.diskSize }}
      deleteClaim: false
{{- end }}