apiVersion: v2
name: helm-dap
description: A Helm chart for Data Analytic Platform

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: influxdb2
    version: "2.1.1"
    repository: "https://helm.influxdata.com/"
    condition: influxdb2.enabled

  - name: grafana
    version: "6.57.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
