apiVersion: v2
name: helm-dap
description: A Helm chart for Data Analytic Platform

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: influxdb2
    version: "2.1.1"
    repository: "https://helm.influxdata.com/"
    condition: influxdb2.enabled

  - name: grafana
    version: "6.57.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled

  - name: "logstash"
    alias: logstash-http-to-kafka
    condition: logstash-http-to-kafka.enabled
    repository: "https://helm.elastic.co"
    version: "8.5.1"

  - name: "kafka"
    alias: kafka
    condition: kafka.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "22.1.6"

#  - name: "kafka-ui"
#    alias: kafka-ui
#    condition: kafka-ui.enabled
#    repository: "https://provectus.github.io/kafka-ui"
#    version: "0.7.0"

  - name: "opensearch"
    alias: opensearch
    condition: opensearch.enabled
    repository: "https://opensearch-project.github.io/helm-charts"
    version: "2.13.1"
