envAlias: production
domainInflux: influx.analytic.prom.co.th
domainGrafana: grafana.analytic.prom.co.th
domainKafka: kafka-ui.analytic.prom.co.th

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.analytic.prom.co.th
      domain: grafana.analytic.prom.co.th
