envAlias: development
domainInflux: influx.analytic-dev.prom.co.th
domainGrafana: grafana.analytic-dev.prom.co.th
domainKafka: kafka-ui.analytic-dev.prom.co.th

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.analytic-dev.prom.co.th
      domain: grafana.analytic-dev.prom.co.th
