influxdb2:
  enabled: true
  fullnameOverride: influxdb

  image:
    tag: 2.7.1-alpine

  env:
    - name: DOCKER_INFLUXDB_INIT_USERNAME
      value: demouser

    - name: DOCKER_INFLUXDB_INIT_PASSWORD
      value: demouser

    - name: DOCKER_INFLUXDB_INIT_ORG
      value: prom

    - name: DOCKER_INFLUXDB_INIT_BUCKET
      value: analytic

    - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      value: edgehello

    - name: DOCKER_INFLUXDB_INIT_MODE
      value: "setup"

  persistence:
    enabled: true
    size: 200Gi

  config:
    http:
      auth-enabled: true

  setDefaultUser:
    enabled: true

grafana:
  enabled: true
  image:
    tag: "9.1.5" #8.5.13 #"9.1.5"

  fullnameOverride: grafana-dap
  envRenderSecret: {}
  #envFromSecrets:
  #  - name: es-soc-basic-authen
  #    optional: false

  datasources: {}
  dashboardProviders: {}
  dashboardsConfigMaps: {}

  grafana.ini:
    #feature_toggles:
    #  enable: disableEnvelopeEncryption
    log:
      level: debug
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD
  extraSecretMounts: []
