### Logstash Http to Kafka ###
logstash-http-to-kafka:
  enabled: true
  antiAffinity: soft

  fullnameOverride: logstash-http-to-kafka
  replicas: 1

  service:
    ports:
      - name: http-input
        port: 8080
        targetPort: 8080
        protocol: TCP

  extraEnvs:
    - name: LS_JAVA_OPTS
      value: "-Xmx2g -Xms2g"

    - name: DUMMY
      value: "001"

  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      pipeline.ecs_compatibility: "disabled"

  logstashPipeline:
    logstash.conf: |
      input {
        http {
          id => "http_input"
          codec => "json_lines"
          port => "8080"
        }
      }

      filter {
        geoip {
          source => "[request][headers][x-real-ip]"
        }
      }

      output {
        #stdout { codec => json_lines }

        kafka {
          bootstrap_servers => "kafka:9092"
          codec => json
          topic_id => "prom-dap"
        }
      }

### InfluxDB ###
influxdb2:
  enabled: true
  fullnameOverride: influxdb

  image:
    tag: 2.7.1-alpine

  env:
    - name: DOCKER_INFLUXDB_INIT_MODE
      value: "setup"

    - name: DOCKER_INFLUXDB_INIT_BUCKET
      value: analytic

    - name: DOCKER_INFLUXDB_INIT_ORG
      value: prom

    - name: DOCKER_INFLUXDB_INIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_USERNAME

    - name: DOCKER_INFLUXDB_INIT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_PASSWORD

    - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

  persistence:
    enabled: true
    size: 200Gi

  config:
    http:
      auth-enabled: true

  setDefaultUser:
    enabled: true

### Grafana ###
grafana:
  enabled: true
  image:
    tag: "9.1.5"

  fullnameOverride: grafana
  envRenderSecret: {}
  envFromSecrets:
    - name: influx-credentials
      optional: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: InfluxDB-DAP
        type: influxdb
        access: Server
        url: http://influxdb
        jsonData:
          version: Flux
          organization: prom
          defaultBucket: analytic
          tlsSkipVerify: true
        secureJsonData:
          token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  dashboardProviders: {}
  dashboardsConfigMaps: {}
  admin:
    existingSecret: "grafana-credentials"
    userKey: GRAFANA_USER
    passwordKey: GRAFANA_PASSWORD
  grafana.ini:
    #feature_toggles:
    #  enable: disableEnvelopeEncryption
    log:
      level: debug
  extraSecretMounts: []


### Kafka ###
kafka:
  enabled: true
  fullnameOverride: kafka
  provisioning:
    enabled: true
    topics:
      - name: prom-dap
        partitions: 1
        replicationFactor: 1
        ## https://kafka.apache.org/documentation/#topicconfigs
        config:
          max.message.bytes: 64000

kafka-ui:
  enabled: true
  fullnameOverride: kafka-ui
  existingSecret: kafka-ui-credential
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: kafka-dap
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      AUTH_TYPE: "LOGIN_FORM" #"DISABLED"
      SECURITY_BASIC_ENABLED: "true"

vector-kafka-to-storage:
  enabled: true
  fullnameOverride: vector-kafka-to-storage
  replicas: 1
  persistence:
    enabled: true
  env:
    - name: DUMMY
      value: "006"

    - name: INFLUXDB_CLOUD_TOKEN
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: INFLUXDB_CLOUD_TOKEN

    - name: GRAFANA_LOKI_USER
      valueFrom:
        secretKeyRef:
          name: vector-credentials
          key: GRAFANA_LOKI_USER

    - name: GRAFANA_LOKI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: vector-credentials
          key: GRAFANA_LOKI_PASSWORD

    - name: ENVIRONMENT
      valueFrom:
        secretKeyRef:
          name: vector-credentials
          key: ENVIRONMENT

  service:
    enabled: false
  serviceAccount:
    create: true
  rbac:
    create: true
  extraVolumeMounts:
    - name: scripts
      mountPath: /scripts/
      readOnly: true
  extraVolumes:
    - name: scripts
      configMap:
        name: vector-filter-cm

  customConfig:
    data_dir: "/vector-data-dir" #Do not change this if you don't know the impact
    sources:
      internal_metrics:
        type: internal_metrics

      kafka_from_http:
        type: kafka
        bootstrap_servers: "kafka:9092"
        group_id: "to-influxdb"
        topics: [ "prom-dap" ]
        decoding:
          codec: json
  
    transforms:
      process_kafka_to_influxdb:
        type: remap
        file: "/scripts/process_kafka_to_influxdb.vrl"
        inputs:
          - kafka_from_http

      process_kafka_to_loki:
        type: remap
        file: "/scripts/process_kafka_to_loki.vrl"
        inputs:
          - kafka_from_http

    sinks:
      #stdout:
      #  type: console
      #  inputs: [process_kafka_to_influxdb]
      #  encoding:
      #    codec: json

      #stdout_raw:
      #  type: console
      #  inputs: [kafka_to_influxdb]
      #  encoding:
      #    codec: json

      influxdb:
        type: "influxdb_logs"
        inputs: [process_kafka_to_influxdb]
        bucket: "analytic"
        endpoint: "https://eu-central-1-1.aws.cloud2.influxdata.com" #"http://influxdb/"
        org: "DevOps" #"prom"
        measurement: "prom-api"
        token: "${INFLUXDB_CLOUD_TOKEN}"
        tags:
          - response_status
          - request_method
          - request_headers_host
          - environment

      loki:
        type: "loki"
        inputs: [process_kafka_to_loki]
        encoding:
          codec: json
        endpoint: "https://logs-prod-011.grafana.net/"
        auth:
          strategy: basic
          user: '475784'
          password: ${GRAFANA_LOKI_PASSWORD}
        labels:
          category: 'prom-api'
          environment: >-
            {{ printf "{{ platform_environment }}" }}
          host: >-
            {{ printf "{{ request.headers.host }}" }}
          method: >-
            {{ printf "{{ request.method }}" }}
          status: >-
            {{ printf "{{ response.status }}" }}
