influxdb2:
  enabled: true
  fullnameOverride: influxdb

  image:
    tag: 2.7.1-alpine

  env:
    - name: DOCKER_INFLUXDB_INIT_MODE
      value: "setup"

    - name: DOCKER_INFLUXDB_INIT_BUCKET
      value: analytic

    - name: DOCKER_INFLUXDB_INIT_ORG
      value: prom

    - name: DOCKER_INFLUXDB_INIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_USERNAME

    - name: DOCKER_INFLUXDB_INIT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_PASSWORD

    - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      valueFrom:
        secretKeyRef:
          name: influx-credentials
          key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

  persistence:
    enabled: true
    size: 200Gi

  config:
    http:
      auth-enabled: true

  setDefaultUser:
    enabled: true

grafana:
  enabled: true
  image:
    tag: "9.1.5" #8.5.13 #"9.1.5"

  fullnameOverride: grafana
  envRenderSecret: {}
  envFromSecrets:
    - name: influx-credentials
      optional: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: InfluxDB-DAP
        type: influxdb
        access: Server
        url: http://influxdb
        jsonData:
          version: Flux
          organization: prom
          defaultBucket: analytic
          tlsSkipVerify: true
        secureJsonData:
          token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  dashboardProviders: {}
  dashboardsConfigMaps: {}
  admin:
    existingSecret: "grafana-credentials"
    userKey: GRAFANA_USER
    passwordKey: GRAFANA_PASSWORD
  grafana.ini:
    #feature_toggles:
    #  enable: disableEnvelopeEncryption
    log:
      level: debug
  extraSecretMounts: []
