influxdb:
  enabled: true
  fullnameOverride: influxdb

  image:
    tag: 2.7.1-alpine

  persistence:
    enabled: true
    size: 200Gi

  config:
    http:
      auth-enabled: true

  setDefaultUser:
    enabled: true
